CREATE TABLE IF NOT EXISTS "Order" (id SERIAL PRIMARY KEY, "userId" INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'pending', total INTEGER NOT NULL, "shippingName" TEXT NOT NULL, "shippingPrice" INTEGER NOT NULL, "receiverName" TEXT NOT NULL, phone TEXT NOT NULL, address TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "OrderItem" (id SERIAL PRIMARY KEY, "orderId" INTEGER NOT NULL, "productId" INTEGER NOT NULL, quantity INTEGER NOT NULL DEFAULT 1, price INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS "Order_userId_idx" ON "Order"("userId");
ALTER TABLE "Order" ADD CONSTRAINT "Order_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Product"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
